#!/bin/bash
#################################################################
#
# Build script template for HipFT.
#
# See the build scripts in the "/build_examples" 
# folder for examples of what to insert here.
# Please do not edit this file, rather copy it to a new 
# file with your own configuration options inserted.
# If your configuration is unique, feel free to add it to the 
# /build_examples folder.
# Note that your build script must be launched from 
# this lowest level directory (not from the build_examples folder).
#
#################################################################
#################################################################
# Enter your MPI compiler (typically "mpif90").
#################################################################

FC=

#################################################################
# Please set the location of the HDF5 include & library files. 
# Make sure the HDF5 LIBRARY is COMPILED with 
# the SAME COMPILER used here, and is in the run-time environment.
#################################################################

HDF5_INCLUDE_DIR=
HDF5_LIB_DIR=

##################################################################
# Please set the HDF5 linker flags to match the installed version.
##################################################################

HDF5_LIB_FLAGS=

###########################################################################
# Please set the compile flags based on your compiler and hardware setup.
###########################################################################

FFLAGS=

###########################################################################
# Specify src filename:  Use hipft_gcc.f90 for GCC, otherwise use hipft.f90
###########################################################################

SRCFILE=

###########################################################################
###########################################################################
###########################################################################

HIPFT_HOME=$PWD

pushd ${HIPFT_HOME}/src >> /dev/null
if [ -e Makefile ]; then
  \rm Makefile
fi 
sed \
  -e "s#<FC>#${FC}#g" \
  -e "s#<FFLAGS>#${FFLAGS}#g" \
  -e "s#<SRCFILE>#${SRCFILE}#g" \
  -e "s#<HDF5_INCLUDE_DIR>#${HDF5_INCLUDE_DIR}#g" \
  -e "s#<HDF5_LIB_DIR>#${HDF5_LIB_DIR}#g" \
  -e "s#<HDF5_LIB_FLAGS>#${HDF5_LIB_FLAGS}#g" \
  Makefile.template > Makefile
echo "make 1>build.log 2>build.err"
make clean
make 1>build.log 2>build.err

echo "cp ${HIPFT_HOME}/src/hipft ${HIPFT_HOME}/bin/hipft"
\cp ${HIPFT_HOME}/src/hipft ${HIPFT_HOME}/bin/hipft

