FC = mpif90

FFLAGS = <FFLAGS> -I<HDF5_INCLUDE_DIR>

OBJS = hipft.o

LDFLAGS = -L<HDF5_LIB_DIR> <HDF5_LIB_FLAGS>

all: $(OBJS)
	$(FC) $(FFLAGS) $(OBJS) $(LDFLAGS) -o hipft
	rm *.mod *.o 2>/dev/null

clean:
	rm -f hipft 2>/dev/null
	rm -f *.mod *.o 2>/dev/null

hipft.o: hipft.f90
	$(FC) -c $(FFLAGS) $<

